/*
 Navicat Premium Dump SQL

 Source Server         : one
 Source Server Type    : MySQL
 Source Server Version : 80039 (8.0.39)
 Source Host           : localhost:3306
 Source Schema         : west_hospital

 Target Server Type    : MySQL
 Target Server Version : 80039 (8.0.39)
 File Encoding         : 65001

 Date: 25/08/2024 15:32:07
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for fill_in
-- ----------------------------
DROP TABLE IF EXISTS `fill_in`;
CREATE TABLE `fill_in`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `form_id` int NOT NULL,
  `form_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `written_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '填写人',
  `written_account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `date` datetime NOT NULL,
  `state` int NOT NULL COMMENT '三种状态 1：待校验  2：校验正确  3：错误',
  `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`, `form_id` DESC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 22 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of fill_in
-- ----------------------------
INSERT INTO `fill_in` VALUES (1, 3, 'test9', '123', '123', '2024-08-24 20:14:11', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false}]');
INSERT INTO `fill_in` VALUES (2, 3, 'test9', '管理员', 'admin', '2024-08-24 22:59:07', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"1\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"11\",\"isNecessary\":true,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"111\",\"isNecessary\":false,\"checkValue\":false}]');
INSERT INTO `fill_in` VALUES (3, 4, 'test2', '管理员', 'admin', '2024-08-24 23:00:30', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"7,8,9\",\"content\":\"7\",\"isNecessary\":true,\"checkValue\":true},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"选项1\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[\"选项1\",\"选项3\"],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"\",\"content\":\"56\",\"isNecessary\":true,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"}],\"content\":[[4,5]]}]');
INSERT INTO `fill_in` VALUES (4, 4, 'test2', '管理员', 'admin', '2024-08-24 23:01:34', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"7,8,9\",\"content\":\"8\",\"isNecessary\":true,\"checkValue\":true},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"}],\"content\":[[4,5]]}]');
INSERT INTO `fill_in` VALUES (7, 3, 'test9', '管理员', 'admin', '2024-08-24 23:36:02', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"96\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false}]');
INSERT INTO `fill_in` VALUES (8, 5, 'wh', '管理员', 'admin', '2024-08-24 23:57:23', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"77\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (9, 5, 'wh', '管理员', 'admin', '2024-08-24 23:57:33', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"1\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"117\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (10, 5, 'wh', '管理员', 'admin', '2024-08-24 23:57:40', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"2\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"22\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"2228\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (11, 5, 'wh', '管理员', 'admin', '2024-08-24 23:57:55', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"3\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"33\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"333\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"选项2\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (12, 5, 'wh', '管理员', 'admin', '2024-08-24 23:58:05', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[\"选项12\",\"选项3\"],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (13, 5, 'wh', '管理员', 'admin', '2024-08-24 23:58:13', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"2024-08-07T16:00:00.000Z\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (14, 5, 'wh', '管理员', 'admin', '2024-08-24 23:58:20', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":10,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]');
INSERT INTO `fill_in` VALUES (16, 5, 'wh', '管理员', 'admin', '2024-08-25 00:53:32', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"7\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"5\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"4\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":0},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":0},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[\"\",\"\",\"\",0,60,\"\"],[\"\",\"\",\"\",0,0,\"\"],[\"\",\"\",\"\",6,0,\"\"],[\"\",\"\",\"\",0,0,\"\"]]}]');
INSERT INTO `fill_in` VALUES (18, 5, 'wh', '管理员', 'admin', '2024-08-25 00:56:01', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":2,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",1,0,\"1\"]]}]');
INSERT INTO `fill_in` VALUES (19, 5, 'wh', 'wh', '123', '2024-08-25 02:14:18', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":500,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",1,0,\"1\"]]}]');
INSERT INTO `fill_in` VALUES (20, 4, 'test2', 'wh', '123', '2024-08-25 02:15:44', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"7,8,9\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"选项2\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"}],\"content\":[[4,5]]}]');
INSERT INTO `fill_in` VALUES (21, 4, 'test2', 'wh', '123', '2024-08-25 02:15:51', 1, '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"7,8,9\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"}],\"content\":[[4,5],[\"\",\"2024-08-26T16:00:00.000Z\"],[\"\",\"\"]]}]');

-- ----------------------------
-- Table structure for forn_list
-- ----------------------------
DROP TABLE IF EXISTS `forn_list`;
CREATE TABLE `forn_list`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `creator` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人',
  `creat_date` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  `table_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `state` int NOT NULL DEFAULT 0 COMMENT '0为关闭，1为开启',
  `filled` int NOT NULL DEFAULT 0 COMMENT '0为没开放过填写 可以编辑，1为开放过填写 不可以编辑',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of forn_list
-- ----------------------------
INSERT INTO `forn_list` VALUES (2, '管理员', '2024-08-24 00:44:49', '1', '1', '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true}]', 1, 1);
INSERT INTO `forn_list` VALUES (3, '管理员', '2024-08-25 00:59:56', 'test9', '测试表，用于测试', '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":true}]', 0, 0);
INSERT INTO `forn_list` VALUES (4, '管理员', '2024-08-24 00:33:29', 'test2', '测试表2', '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"7,8,9\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"}],\"content\":[[4,5]]}]', 0, 1);
INSERT INTO `forn_list` VALUES (5, '管理员', '2024-08-24 23:38:54', 'wh', '测试用，用于测试表单所有类型组件填写', '[{\"type\":7,\"uniqueName\":\"\",\"label\":\"人员ID\",\"suggestion\":\"\",\"content\":\"\",\"isNecessary\":true,\"checkValue\":true},{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行输入框\",\"max\":10,\"min\":0,\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":2,\"uniqueName\":\"\",\"label\":\"单选框\",\"select\":\"\",\"content\":[\"选项1\",\"选项2\"],\"isNecessary\":false},{\"type\":3,\"uniqueName\":\"\",\"label\":\"多选框\",\"select\":[],\"content\":[\"选项1\",\"选项12\",\"选项3\"],\"isNecessary\":false},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":10,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":1000,\"min\":0,\"content\":0,\"isNecessary\":false,\"checkValue\":false},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议框\",\"suggestion\":\"1,4,5,6\",\"content\":\"\",\"isNecessary\":false,\"checkValue\":false},{\"type\":20,\"uniqueName\":\"\",\"label\":\"自增表格\",\"header\":[\"列1\",\"列2\",\"列3\",\"列4\",\"列5\",\"列6\"],\"bodyForm\":[{\"type\":0,\"uniqueName\":\"\",\"label\":\"单行输入框\",\"max\":10,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":1,\"uniqueName\":\"\",\"label\":\"多行文本\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":4,\"uniqueName\":\"\",\"label\":\"日期选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":5,\"uniqueName\":\"\",\"label\":\"数量选择\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":6,\"uniqueName\":\"\",\"label\":\"滑动条\",\"max\":100,\"min\":0,\"suggestion\":\"\",\"content\":\"\"},{\"type\":7,\"uniqueName\":\"\",\"label\":\"带建议输入\",\"max\":100,\"min\":0,\"suggestion\":\"9,8,7\",\"content\":\"\"}],\"content\":[[4,5,\"1\",\"1\",\"1\",\"1\"]]}]', 0, 0);

-- ----------------------------
-- Table structure for logs
-- ----------------------------
DROP TABLE IF EXISTS `logs`;
CREATE TABLE `logs`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `user` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `controls` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `controls_date` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 16 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of logs
-- ----------------------------
INSERT INTO `logs` VALUES (1, 'wh', '123', '登录', '2024-08-25 03:56:07');
INSERT INTO `logs` VALUES (2, '管理员', 'admin', '登录', '2024-08-25 03:25:29');
INSERT INTO `logs` VALUES (3, 'wh', '123', '登录', '2024-08-25 03:26:58');
INSERT INTO `logs` VALUES (4, '管理员', 'admin', '登录', '2024-08-25 03:27:02');
INSERT INTO `logs` VALUES (5, '管理员', 'admin', '登录', '2024-08-25 03:42:56');
INSERT INTO `logs` VALUES (6, '管理员', 'admin', '登录', '2024-08-25 03:49:10');
INSERT INTO `logs` VALUES (7, '管理员', 'admin', '登录', '2024-08-25 03:49:32');
INSERT INTO `logs` VALUES (8, '管理员', 'admin', '登录', '2024-08-25 03:50:44');
INSERT INTO `logs` VALUES (9, '管理员', 'admin', '登录', '2024-08-25 03:57:27');
INSERT INTO `logs` VALUES (10, '管理员', 'admin', '登录', '2024-08-25 04:09:57');
INSERT INTO `logs` VALUES (11, '管理员', 'admin', '登录', '2024-08-25 05:09:06');
INSERT INTO `logs` VALUES (12, 'wh', '123', '登录', '2024-08-25 05:21:23');
INSERT INTO `logs` VALUES (13, '管理员', 'admin', '登录', '2024-08-25 05:25:13');
INSERT INTO `logs` VALUES (14, '管理员', 'admin', '登录', '2024-08-25 05:32:36');
INSERT INTO `logs` VALUES (15, '管理员', 'admin', '登录', '2024-08-25 05:44:34');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `power` tinyint NOT NULL COMMENT '为1时是管理员，0时是普通用户',
  `roles` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '页面权限',
  `create_date` timestamp NOT NULL,
  PRIMARY KEY (`account`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('123', '123', 'wh', '14705253625', 0, '[\'自定义表单\',\'表单列表\',\'表单填写\']', '2024-08-25 04:13:03');
INSERT INTO `user` VALUES ('admin', 'admin', '管理员', '14536253625', 1, 'admin', '2024-08-24 02:13:07');

SET FOREIGN_KEY_CHECKS = 1;
